version: 1
formatters:
  json:
    '()': ekgclf.utils.logfmt.JsonFormatter
    fmt: '%(asctime)s %(levelname)s %(name)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    level: INFO
loggers:
  ekgclf:
    level: INFO
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console]
